site_name: Research Support

theme:
  name: material
  features:
    - toc.integrate

nav:
  - index.md
  - links.md
  - Sites &amp; Services:
    - pure.md
    - scival.md
    - funding-institutional.md
  - Guides:
    - ref.md
    - the-publication-journey.md
    - datasets.md
    - metrics.md
    - research-impact.md
    - affiliation.md
    - citation-management.md
    - open-access.md

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html

extra_css: [extra.css]